import { useEffect, useRef, useState } from 'react';
import { Camera, Download, Share2, Trash2, Upload, X } from 'lucide-react';
import { html2canvas } from '../utils/capture';
import { clearCaptures, downloadCapture, importScreenshot, listCaptures, removeCapture, saveCapture, shareCapture, objectUrl, type LocalCapture } from '../services/screenshotService';
import { useOverlayPresence } from '../motion/useOverlayPresence';

function CaptureImage({item,alt}:{item:LocalCapture;alt:string}){const [url,setUrl]=useState('');useEffect(()=>{if(!(item.blob instanceof Blob)){setUrl('');return}const u=objectUrl(item);setUrl(u);return()=>URL.revokeObjectURL(u)},[item]);if(!url)return <div className="capture-missing" aria-hidden="true"/>;return <img src={url} alt={alt} loading="lazy" decoding="async"/>;}

export function CaptureWallet({language,embedded=false}:{language:'ar'|'en';embedded?:boolean}){
 const ar=language==='ar'; const [open,setOpen]=useState(false); const [items,setItems]=useState<LocalCapture[]>([]); const [busy,setBusy]=useState(false); const input=useRef<HTMLInputElement>(null);
 const refresh=()=>listCaptures().then(x=>setItems(x.sort((a,b)=>b.createdAt-a.createdAt)));
 const{backdropRef,panelRef,requestClose}=useOverlayPresence<HTMLButtonElement,HTMLElement>('drawer',()=>setOpen(false),open);
 useEffect(()=>{refresh()},[]);
 const capture=async()=>{setBusy(true);try{const canvas=await html2canvas(document.body);await saveCapture(canvas.toDataURL('image/png'),'TAAMEN capture')}finally{setBusy(false);refresh();setOpen(true)}};
 const imported=async(file?:File)=>{if(!file)return;try{await importScreenshot(file);await refresh();setOpen(true)}catch{}};
 return <><div className={embedded?'capture-trigger-row':'capture-actions'}>{embedded&&<><span><strong>{ar?'محفظة اللقطات':'Screenshot Wallet'}</strong><small>{ar?'حفظ وإدارة اللقطات محليًا.':'Manage local screenshots.'}</small></span><button className="dark-action" onClick={()=>{setOpen(true);refresh()}}><Upload size={15}/>{ar?'فتح المحفظة':'Open wallet'}</button></>}{!embedded&&<><button className="icon-button capture-button" onClick={capture} disabled={busy} aria-label={ar?'التقاط الشاشة':'Capture screen'} title={ar?'التقاط الشاشة':'Capture screen'}>{busy?<span className="capture-spinner"/>:<Camera size={17}/>}</button><button className="icon-button" onClick={()=>{setOpen(true);refresh()}} aria-label={ar?'محفظة اللقطات':'Screenshot wallet'} title={ar?'محفظة اللقطات':'Screenshot wallet'}><Upload size={16}/></button></>}</div>
 {open&&<div className="capture-wallet"><button ref={backdropRef} className="overlay-backdrop" aria-label={ar?'إغلاق':'Close'} onClick={requestClose}/><section ref={panelRef} className="capture-panel"><header><div><p className="eyebrow">TAAMEN / CAPTURE</p><h2>{ar?'محفظة اللقطات':'Screenshot Wallet'}</h2></div><button className="icon-button" aria-label={ar?'إغلاق':'Close'} onClick={requestClose}><X size={16}/></button></header><div className="capture-toolbar"><button className="dark-action" onClick={capture} disabled={busy}><Camera size={15}/>{ar?'التقاط الشاشة':'Capture screen'}</button><button className="dark-action" onClick={()=>input.current?.click()}><Upload size={15}/>{ar?'استيراد لقطة':'Import screenshot'}</button><input ref={input} hidden type="file" accept="image/*" onChange={e=>imported(e.target.files?.[0])}/><button className="text-button" onClick={async()=>{if(!window.confirm(ar?'حذف كل اللقطات؟':'Delete all captures?'))return;await clearCaptures();refresh()}}><Trash2 size={14}/>{ar?'حذف الكل':'Clear all'}</button></div><div className="capture-grid">{items.map(item=><article className="capture-card" key={item.id}><CaptureImage item={item} alt={item.name}/><div><small>{new Date(item.createdAt).toLocaleString(ar?'ar-PS':'en-GB')}</small><div className="capture-card-actions"><button className="mini-action" onClick={()=>downloadCapture(item)}><Download size={13}/>{ar?'حفظ':'Download'}</button><button className="mini-action" onClick={async()=>{try{await shareCapture(item)}catch{}}}><Share2 size={13}/>{ar?'مشاركة':'Share'}</button><button className="mini-action" onClick={async()=>{await removeCapture(item.id);refresh()}}><Trash2 size={13}/></button></div></div></article>)}{!items.length&&<div className="empty-state"><Camera/><strong>{ar?'لا توجد لقطات بعد':'No captures yet'}</strong><span>{ar?'التقط الشاشة أو استورد صورة من جهازك.':'Capture the screen or import an image from your device.'}</span></div>}</div></section></div>}</>;
}
